version: "3.8"

services:
  frontend:
    image: grosourstenebreux03/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    image: grosourstenebreux03/backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: mydb
    networks:
      - mynetwork

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  dbdata:

networks:
  mynetwork:
